version: '3.9'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      # NOTE: need to match DB_*** env vars in Laravel project .env file
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - laravel_network

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - laravel_repo:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_network

  webdev:
    build:
      context: ./webapp
      dockerfile: Dev.Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 5173:5173
    volumes:
      - laravel_repo:/var/www/html
      # NOTE: mount webapp project folder to web container to enable hot reload
      - ./webapp:/var/www/html/web:cached
      # NOTE: exclude these files and folders from host
      - /var/www/html/web/node_modules/
      - /var/www/html/web/pnpm-lock.json
    depends_on:
      - laravel
    networks:
      - laravel_network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 80:80
    restart: unless-stopped
    tty: true
    volumes:
      - laravel_repo:/var/www/html
    depends_on:
      - laravel
    networks:
      - laravel_network

volumes:
  dbdata:
    driver: local
  laravel_repo:
    driver: local

networks:
  laravel_network:
    driver: bridge
